"""empty message

Revision ID: e84a3f097509
Revises: 
Create Date: 2021-04-28 13:34:54.227957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e84a3f097509'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Owners',
    sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('owner_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), nullable=False),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('Pets',
    sa.Column('pet_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('pet_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('booking_time', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('room_num', sa.SMALLINT(), nullable=False),
    sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['Owners.owner_id'], ),
    sa.PrimaryKeyConstraint('pet_id')
    )
    op.create_table('Activities',
    sa.Column('activity_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('activity_time', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('pet_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['Pets.pet_id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Activities')
    op.drop_table('Pets')
    op.drop_table('Owners')
    # ### end Alembic commands ###
